---
# StorageClass for es storage
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: es-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
# PersistentVolume for Worker Data 1
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data-pv-1
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: es-storage
  local:
    path: /data/elasticsearch/es-data-pv  # Path on the data worker node
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: elastic-data
          operator: In
          values:
          - "true"  # Must match the node label
---
# PersistentVolume for Worker Data 2
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data-pv-2
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: es-storage
  local:
    path: /data/elasticsearch/es-data-pv  # Path on the data worker node
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: elastic-data
          operator: In
          values:
          - "true"  # Must match the node label
---
# PersistentVolume for Worker Data 3
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data-pv-3
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: es-storage
  local:
    path: /data/elasticsearch/es-data-pv  # Path on the data worker node
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: elastic-data
          operator: In
          values:
          - "true"  # Must match the node label
---
# PV for Ingest 1
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-ingest-pv-1
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: es-storage
  local:
    path: /data/elasticsearch/es-ingest-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: elastic-ingest
          operator: In
          values:
            - "true"
---
# PV for Master 1
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-master-pv-1
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: es-storage
  local:
    path: /data/elasticsearch/es-master-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: elastic-master
          operator: In
          values:
            - "true"