@Library('jenkins-interpay-lib-main')_
import pipeline.fe.FePipeline

def fePipeline

pipeline {
    agent any
    tools { nodejs "NodeJS" }

    environment {
        SOURCE_URL = 'url-to-your-webapp-repository'
        ARGO_REPO_URL = 'url-to-your-cd-repository'
        DEPLOY_ENV = 'dev'
        APP_NAME = 'interpay'
        SERVICE_NAME = 'webapp'
        TIMEZONE = 'Asia/Ho_Chi_Minh'
    }

    stages {
        stage('Run Frontend Pipeline') {
            steps {
                script {
                    fePipeline = new FePipeline(this)
                    fePipeline.run("${SOURCE_URL}", "${ARGO_REPO_URL}", "${DEPLOY_ENV}", "${APP_NAME}", "${SERVICE_NAME}", "${TIMEZONE}")
                }
            }
        }

        stage('Clean Up Workspace') {
            steps {
                deleteDir()
            }
        }
    }
}